#!/bin/bash
#SBATCH --partition=rome
#SBATCH --job-name=HFDownloadModel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --mem=8G
#SBATCH --output=/home/eboccaletti/models/job_outputs/slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd /home/eboccaletti

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate initial_env

python -u /home/eboccaletti/models/download_model.py "$@"