#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=CheckVLMEnv
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=/home/eboccaletti/thesis_project/job_outputs/slurm_check_vlm_env_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source /sw/arch/RHEL9/EB_production/2025/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate vlm_gpu
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

# srun python -uc "import torch; print('GPU available?', torch.cuda.is_available()); if torch.cuda.is_available():
#     print("GPU:", torch.cuda.get_device_name(0))"

srun python -u - <<EOF
import torch
print("GPU available?", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
EOF