#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=/home/eboccaletti/thesis_project/job_outputs/slurm_check_env_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_gpu
# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"