#!/bin/bash
#SBATCH --partition=rome
#SBATCH --job-name=ExtractMOMENTSFrames
#SBATCH --output=/home/eboccaletti/thesis_project/job_outputs/extract_moments_frames_%j.out
#SBATCH --error=/home/eboccaletti/thesis_project/job_outputs/extract_moments_frames_%j.err
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=02:00:00

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate vlm_qwen_reproducing_env

set -euo pipefail

cd $HOME

echo "=== Extract MOMENTS Frames ==="
echo "Host: $(hostname)"
echo "Start time: $(date)"

python /home/eboccaletti/thesis_project/data_generation/extract_moments_frames.py \
    --moments_dir /home/eboccaletti/thesis_project/data/MOMENTS \
    --output_dir  /home/eboccaletti/thesis_project/data/MOMENTS/frames \
    --n_frames 10

echo "End time: $(date)"
