#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=GenerateCountingImages
#SBATCH --output=/home/eboccaletti/reproducing_code/job_outputs/gen_count_imgs_%j.out
#SBATCH --error=/home/eboccaletti/reproducing_code/job_outputs/gen_count_imgs_%j.err
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=12:00:00

module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_qwen_reproducing_env

set -euo pipefail

cd $HOME

echo "=== Generate Counting Images ==="
echo "Host: $(hostname)"
echo "Start time: $(date)"
echo "Working dir: $(pwd)"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-unset}"

nvidia-smi || true

python /home/eboccaletti/reproducing_code/vlm-circuits-analysis/data_generation/generate_counting_images.py   --prompt_template_idx 0   --seeds 42 43 44 45 46

echo "End time: $(date)"