#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=RenameCountingImages
#SBATCH --output=/home/eboccaletti/reproducing_code/job_outputs/rename_count_imgs_%j.out
#SBATCH --error=/home/eboccaletti/reproducing_code/job_outputs/rename_count_imgs_%j.err
#SBATCH --cpus-per-task=4
#SBATCH --mem=12G
#SBATCH --time=1:00:00

#gpus=1
module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_qwen_reproducing_env

set -euo pipefail

cd $HOME

echo "=== Renaming counting images ==="
echo "Start: $(date)"

python /home/eboccaletti/reproducing_code/vlm-circuits-analysis/data_generation/rename_counting_images.py

echo "End: $(date)"