#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=Qwen_Lcounting_NodeCircuit_gpu_h100
#SBATCH --output=/home/eboccaletti/reproducing_code/job_outputs/qwen_node_circuit_gpu_h100_Lcounting_%j.out
#SBATCH --error=/home/eboccaletti/reproducing_code/job_outputs/qwen_node_circuit_gpu_h100_Lcounting_%j.err
#SBATCH --cpus-per-task=9
#SBATCH --mem=80G
#SBATCH --time=24:00:00

module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_qwen_reproducing_env

set -euo pipefail

cd /home/eboccaletti/reproducing_code/vlm-circuits-analysis

echo "=== Qwen node circuit: counting job - language only ==="
echo "Host: $(hostname)"
echo "Start time: $(date)"
echo "Working dir: $(pwd)"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-unset}"

nvidia-smi || true

python script_node_circuit_discovery_and_eval.py \
  --model_name qwen2-7b-vl-instruct \
  --model_path /home/eboccaletti/models/qwen2vl7b \
  --task_name counting \
  --ap_ig_steps 5 \
  --language_only

echo "End time: $(date)"

# --model_name Qwen/Qwen2-VL-7B-Instruct \