#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=Qwen_arithmetic_NodeCross_gpu_h100
#SBATCH --output=/home/eboccaletti/reproducing_code/job_outputs/qwen_node_cross_gpu_h100_arithmetic_%j.out
#SBATCH --error=/home/eboccaletti/reproducing_code/job_outputs/qwen_node_cross_gpu_h100_arithmetic_%j.err
#SBATCH --cpus-per-task=9
#SBATCH --mem=80G
#SBATCH --time=12:00:00

module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_qwen_reproducing_env

set -euo pipefail

cd /home/eboccaletti/reproducing_code/vlm-circuits-analysis

echo "=== Qwen node cross modality: arithmetic job ==="
echo "Host: $(hostname)"
echo "Start time: $(date)"
echo "Working dir: $(pwd)"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-unset}"

nvidia-smi || true

python script_node_cross_modality_analysis.py \
  --model_name qwen2-7b-vl-instruct \
  --model_path /home/eboccaletti/models/qwen2vl7b \
  --task_name arithmetic \
  --l_circuit_percentage 0.01 \
  --vl_circuit_percentage 0.03

echo "End time: $(date)"


# recall: "--l_circuit_percentage", type=float, help="For which percentage of components in the L circuit to analyze cross-modality functionallity",
# recall: "--vl_circuit_percentage", type=float, help="For which percentage of components in the VL circuit to analyze cross-modality functionallity",