#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=Qwen_BackpatchingExp_arithmetic_gpu_h100
#SBATCH --output=/home/eboccaletti/reproducing_code/job_outputs/qwen_backpatching_exp_gpu_h100_arithmetic_%j.out
#SBATCH --error=/home/eboccaletti/reproducing_code/job_outputs/qwen_backpatching_exp_gpu_h100_arithmetic_%j.err
#SBATCH --cpus-per-task=9
#SBATCH --mem=80G
#SBATCH --time=24:00:00

module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment
source activate vlm_qwen_reproducing_env

set -euo pipefail

cd /home/eboccaletti/reproducing_code/vlm-circuits-analysis

echo "=== Qwen Backpatching Experiment: arithmetic job ==="
echo "Host: $(hostname)"
echo "Start time: $(date)"
echo "Working dir: $(pwd)"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-unset}"

nvidia-smi || true

python script_backpatching_experiment.py \
  --model_name qwen2-7b-vl-instruct \
  --model_path /home/eboccaletti/models/qwen2vl7b \
  --task_name arithmetic \
  --src_layer_range 6 19 \
  --dst_layer_range 0 13

echo "End time: $(date)"

# recall: "--src_layer_range", type=int, nargs=2, help="The layer range to backpatch from"
# recall: "--dst_layer_range", type=int, nargs=2, help="The layer range to backpatch to"
# recall: "--task_name", type=str, choices=SUPPORTED_TASKS, help="Name of the task to be localized",

# Paper says:  Best back-patching settings. Each cell presents the lsrc, ldst and layer window size (in parenthesis) that leads to the highest back-patching accuracy.
# Model: Qwen2-7B-VL
# Task: arithmetic
# Best settings:  11 → 7 (3)